### ISSUE TITLE
A solution for continuous deployment.

### ISSUE THREAD

**Issue by hosseinzoda** [openassistive/OpenATFrontEnd#10]
# Why It's needed?
1. Netlify has request rate limit. https://www.netlify.com/docs/api/#rate-limiting
2. Making it reliable and scalable 

# My suggestion

By setting up deploy window we can fix this issue. 

## What's good about it
1. We can determine the next deploy time and show it to the user.
2. The current setup is compatible with it.

Core: Depending on few variables and the state of deployment determine next `deploy or git push trigger`

**Comment by willwade** [comment]
I did wonder if we deploy directly in api. It's more work though.. and could be tricky to create the heroku buildpack. But yeah - I can see the benefit

**Comment by hosseinzoda** [comment]
I did look at that too. We can do it, But `git push` works as well.

**Comment by hosseinzoda** [comment]
This issue should be on backend. I'll move it there.

**Comment by hosseinzoda** [comment]
moved openassistive/OpenATBackend#10
