### ISSUE TITLE
Deal with 'un-moderated' (or draft) items

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATFrontEnd#12]
Either 
1. Tag all items via /save to be 'un-moderated' and hide all 'un-moderated' items front front facing list views (but create a list view of all items 'un-moderated' and edit single template to highlight this 'un-moderated' item)
~2. Use draft feature of hugo and don't display at all (but change alert for duplicate to link to GitHub item instead of a page).~

see https://github.com/openassistive/OpenATBackend/issues/12

GO with 1.

**Comment by hosseinzoda** [comment]
Done
