### ISSUE TITLE
Bugs and issues: Download with service image

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATFrontEnd#13]
(Just creating new issue as #3 is getting really messy!)

From: 
https://github.com/openassistive/OpenATFrontEnd/issues/3#issuecomment-293185547

**Comment by hosseinzoda** [comment]
I did check #3 issues.
Except #14 only change i made was, To make width for text of items smaller. In my opinion it looks better.
So the links and image will be on right for wider range of screen size.
