### ISSUE TITLE
change service name lookup for image 

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATFrontEnd#14]
I think we need to change https://github.com/openassistive/hugo-tranquilpeak-theme/blob/master/layouts/item/single.html#L38

and deal with this somehow here as well as (/instead of?) relying on service_name. Reason being is we need to deal with the fact that items may be added without backend and this seems a bit un-neccessary for the front matter.

so something like

var patt = new RegExp("^(?:.(?=....*).)?([^.]+)"); // (https://regex101.com/r/zH5jG7/1)
service_name = patt.exec(project_url);

(from #3 )

**Comment by hosseinzoda** [comment]
Done

**Comment by willwade** [comment]
thanks
