### ISSUE TITLE
Add Debug mode

### ISSUE THREAD

**Issue by hosseinzoda** [openassistive/OpenATFrontEnd#15]
To `dryrun` the submit operation you need to add the following at the end of Project Url.
`__DRYRUN__`
Like so.
![screenshot from 2017-04-18 13-14-11](https://cloud.githubusercontent.com/assets/21030850/25125860/fe966484-2438-11e7-9dfa-ec23b15cb5ba.png)

**Comment by willwade** [comment]
awesome. thanks
