### ISSUE TITLE
Algolia search support

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATFrontEnd#18]
This relates to https://github.com/kakawait/hugo-tranquilpeak-theme/issues/8 - I think we may need to work on this ourselves. What it entails:
- Creating a service (e.g. npm run aloglia-index) that indexes all content/items /posts etc.. and pushes to algolia
- Building the frontend (I think the majority of this is as actually done since its done in the upstream hexo version of this here: http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/#search). Its largely commented out right now in our code.

Will need thinking about this.

Some further notes. I asked Netlify how we could do it.. they suggested putting it in a npm script.. 

> we run npm install for you automatically if you ship us a package.json.  We do this before the build - so everything is there for 'hugo -b domain' or whatever command you use.  You can run it again if you want..but you shouldn't have to if your package.json has everything you need to build the site (that is, everything you'd need to build the site on a new computer - without any packages installed globally w/'npm install -g')
> you can run multi-step build commands - just set it to something like npm run index-site && hugo -b domain .  Our build container is pretty capable and is just a linux shell
> caveat:  your build needs to finish in 15 minutes or less.

This may be useful. Note the scripts to do the indexing at the bottom: https://github.com/noahgift/hugotools

NB: We would need to create an indexer script that indexes first /post but then our /items. We should push to the upstream project and allow that project to maintain the /post script if needed :)

**Comment by willwade** [comment]
(If you want to just focus on /items for now thats fine. I'm hearing what you are saying about supporting the upstream project)

**Comment by hosseinzoda** [comment]
I did not perform extra work(refinement) on this issue. 

only items reindex is implemented. And it's connected with netlify now. So new entries should get indexed.

UI part is working. It's pretty basic, We can add auto-complete, loading indicator. Or even getting it out of popup form.

**Comment by hosseinzoda** [comment]
I did found the already existing implementation of algolia on the theme. So i just did fixed the issues related to that.
