### ISSUE TITLE
Hardware and Software - different tags

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATFrontEnd#24]
I'm starting to wonder if we need a different set of tags - and thus two different tags pages - for hardware and software.

**Comment by hosseinzoda** [comment]
@willwade I think all or partial tags should not be specific for hardware or software. I can't bring a case which proves this.
This thought is from the way the tags and categories are structured.

**Comment by paulhewett** [comment]
Not required currently - will continue with tags for both hardware and software for now and review soon.
