### ISSUE TITLE
Handling of wider projects

### ISSUE THREAD

**Issue by paulhewett** [openassistive/OpenATFrontEnd#29]
We need to look at wider 'infrastructure' projects could be managed, like WWAAC etc.

**Comment by willwade** [comment]
Agreed. And also editorial workflow going forward. I'm wondering about volunteer section editors.

**Comment by willwade** [comment]
I've done some tidying for this.. Using the framework tag https://openassistive.org/tags/#framework-list

NB: @joereddington was asking about this one. Think it does the job for now
