### ISSUE TITLE
Re-style list & item pages

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATFrontEnd#3]
The archetype for item has images and a download link. We need to style both single and list templates highlighting these (if the post has them)

**Comment by hosseinzoda** [comment]
1. I'll change `archetypes/item.md`  `image` and `thumb` to empty string. So we know It's empty.
2. I'll modify all content items where `image` and `thumb` does not exists to empty string.

ps. I see some items do have image with low quality.

**Comment by willwade** [comment]
If empty delete the whole var instead. Because the api will do this going forward (having empty strings is messy in yaml)

**Comment by hosseinzoda** [comment]
ok

**Comment by willwade** [comment]
PS: re: images. Sure. I don't think may have images (maybe sawat?) - all depends on the original source (e.g. they are from here which are pretty crappy: https://sourceforge.net/projects/sawat/). Images will naturally be a really random quality and size.. Anything we can/should do, do you think?

**Comment by willwade** [comment]
PPS: and images - you can delete all entries that look like this:

`image:` "images/full/3.png"
thumb: "images/thumbs/3.png"`

(i.e images/full/([0-9]+).png ) 

They were from a previous attempt at theming this site and are just placeholders

**Comment by hosseinzoda** [comment]
Alright. I'll come up with some styling. And then we can decide what can improve displaying small images.

**Comment by hosseinzoda** [comment]
We need to modify variable `type` to `project_type`. It's interfering with hugo type which is not convenient.
If we continue as is. I've to create a layout for each type.

**Comment by hosseinzoda** [comment]
`images` are not accessible at root directory i need to move it to static folder.
There's already a folder called `images` there. I think if we add it in a new directory `files/images` will be good.

**Comment by hosseinzoda** [comment]
Uploaded images are in square size. That's good for thumb to be shown on lists, For single page wide looks better.

Square is of when i did pull the image to right.

**Comment by hosseinzoda** [comment]
For lists i see Categories, Tags. But not item itself, tag or category.
Is this something need fixing?
Should i add image and download to categories and tags page?

**Comment by willwade** [comment]
Re; renaming. Let's call the type "project". Will that work? 

Yes - move images (I'll fix in api - or you  can if you want ( it's the line "      contentCreator.SaveImagesToGitHub(json.image_download, json.short_title, 'images/');" in https://github.com/openassistive/OpenATBackend/blob/master/js/savejson/savejson.controller.js )

Re: image width. What if original image a square? The incoming images are going to be all sorts of sizes. Not sure what to do. - any suggestions?

Re: lists. I'm not following you on this one. Mind explaining that again? Sorry!

**Comment by hosseinzoda** [comment]
> Re: image width. What if original image a square? The incoming images are going to be all sorts of sizes. Not sure what to do. - any suggestions?

We can leave this for now.

> Re: lists. I'm not following you on this one. Mind explaining that again? Sorry!

In issue description you mentioned.
> We need to style both single and list templates highlighting these (if the post has them)

list templates is what I'm referring. I did the single mode. Can you send me example of current list so i know where should i change?

okay to the rest.

**Comment by hosseinzoda** [comment]
@willwade Please take look. single page only. Tell me what you think.

**Comment by willwade** [comment]
Cool. Just had a look properly. Looks good. Just scribbled some thoughts on a screenshot..

In short:
- Not sure what to do about screenshots. I wonder about cropping to wide images.. (NB: means changing this line: https://github.com/openassistive/OpenATBackend/blob/master/js/functions.js#L110) 
- Date is appearing wrong. Im guessing we aren't using the correct field in the markdown. Guessing we need date: 2014-08-16 (I propose we need the entered date as well as dateMod (dateMod is date the project was modified). https://github.com/openassistive/OpenATBackend/issues/3
- Somehow we need to show (or link) to the original project_url. Any good ideas?!
- We need to somehow reference the original content publisher (e.g. Instructables, Pinshape etc.). One idea: change the "download" arrow to be the content publishers logo. Or in the text (Download (in smaller text: "via Instructables") - what do you think would work better?

<img width="817" alt="screen shot 2017-04-03 at 09 26 48" src="https://cloud.githubusercontent.com/assets/229352/24601341/6874b80a-1850-11e7-8404-acb609c1f7c8.png">

**Comment by willwade** [comment]
Ok Lists.. Its not major changes to be honest.. 

Here's what I envisaged:

- A list for hardware which also is accessible by tags. e.g. https://openassistive.org/tags (so it would just be hardware). I was wondering about using the thumbnails in this list but not sure. 
- Similarly for software. 
- We could then ditch the "Categories" link on the toolbar. And just have two - software and hardware links. 
- We also need a list of all items in most recent order. To be honest this is probably just using the archives feature (https://tranquilpeak.kakawait.com/archives/)

**Comment by hosseinzoda** [comment]
I'll perform your request on lists. I guess there's few changes to fix these.

>  Not sure what to do about screenshots. I wonder about cropping to wide images.. (NB: means changing this line: https://github.com/openassistive/OpenATBackend/blob/master/js/functions.js#L110)

I think we should take the screenshot as is. And use scale-to-fit method to fit the image on screen. We can also take a certain image sizes as best to fit on screen. resize should be based on the ratio of image and some min/max parameters. I'll work on that (if you see it's needed)


I think datemod is not used. To get fixed.

> Somehow we need to show (or link) to the original project_url. Any good ideas?!

It would be good if we use these service's icon.

> We need to somehow reference the original content publisher (e.g. Instructables, Pinshape etc.). One idea: change the "download" arrow to be the content publishers logo. Or in the text (Download (in smaller text: "via Instructables") - what do you think would work better?

We can have two buttons for each url. And for link to original_url we can use the service name or specific name depending on it. like "Github Repository"

**Comment by hosseinzoda** [comment]
If you resize the window to bigger size. Image and download link will go to right. I tried to not change size of content.

**Comment by willwade** [comment]
One more thing needed on the single item view: 
- "Is something wrong with this entry? Get in touch with us" (link to the contact form).

**Comment by hosseinzoda** [comment]
This is what i end up with single item. (I have hard time figuring out a good styling for it)
![screenshot from 2017-04-07 23-42-06](https://cloud.githubusercontent.com/assets/21030850/24819428/4004815c-1bed-11e7-8242-f1b9ff2e5722.png)
![screenshot from 2017-04-07 23-42-25](https://cloud.githubusercontent.com/assets/21030850/24819452/527f1946-1bed-11e7-909e-8ace00729f3e.png)

1. for `download/project_link` to be with the right name. item `params` should contain `service_name` (i did add it on backend)  
2. Category list is working good now. It has image.
3. Date will get alright when new entries has added. (current items need change to work)
4. All texts/icons about `download/project_link` are stored on `i18n`, They may need change.

**Comment by willwade** [comment]
Should https://openassistive.org/item/reaction-test-01/ be showing the gitHub image?

**Comment by hosseinzoda** [comment]
@willwade This features requires a new field in front-matter. service_name: github/pinshape/etc
I did add it on backend. Only new add project will do it.

**Comment by willwade** [comment]
ok just done that: https://openassistive.org/item/reaction-test-01/ (https://github.com/openassistive/OpenATFrontEnd/blob/master/content/item/reaction-test-01.md)

**Comment by hosseinzoda** [comment]
I did try to add it. This is not working right now. I have to check the issue.

**Comment by willwade** [comment]
Got this now. OK so its service_name that is being added to front matter. A couple of small issues:

I think we need to change https://github.com/openassistive/hugo-tranquilpeak-theme/blob/master/layouts/item/single.html#L38 

and deal with this somehow here as well as (/instead of?) relying on service_name. Reason being is we need to deal with the fact that items may be added without backend and this seems a bit un-neccessary for the front matter. 

so something like 

var patt = new RegExp("^(?:.*(?=\..*\..*).)?([^.]+)");  // (https://regex101.com/r/zH5jG7/1) 
service_name =  patt.exec(project_url);

**Comment by willwade** [comment]
closing this for now
