### ISSUE TITLE
Error: description required but no field for entry

### ISSUE THREAD

**Issue by paulhewett** [openassistive/OpenATFrontEnd#31]
![Error Message](https://user-images.githubusercontent.com/2620062/29684380-ad63b89c-8909-11e7-9b2c-a90bf2307bec.png)

Adding new project from 
http://www.instructables.com/id/No-Solder-Battery-Interrupter/

**Comment by willwade** [comment]
I think this should be fixed by the scraper in the backend.. But I also think we should provide a short description and long description text to the frontend

**Comment by hosseinzoda** [comment]
Instructables has changed its html structure so it does not have selector `p.description`.

There's description for the page. I think this is good to be used for "description".

Here's what we can use for "main_description" except being equal "description".
- There's series of steps in for each project. we can use one or more of these steps. It might not be relevant.

@willwade @paulhewett What do you think?

**Comment by willwade** [comment]
Ok. 

Short description - look at the header (name="description" content="..) 

Long description - you are right

@hosseinamin - not sure if useful - but take a look at the "script type="application/ld+json">" - there is a json object with a lot of what we need. Maybe more reliable than the html??

@hosseinamin - I forgot to say - for the frontend - we could do with editing the short description when we add.
