### ISSUE TITLE
when entering 's' into contact or add form causes search to appear

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATFrontEnd#32]
The 's' keyboard shortcut is neat - but we need to ignore if the contact modal is open - or we are on the add form.

**Comment by hosseinzoda** [comment]
@willwade I didn't understand what you mean.
Can you elaborate?

**Comment by willwade** [comment]
Type the letter s on any page and it brings up the search box. It’s a keyboard shortcut. But causes a problem when filing in a form
