### ISSUE TITLE
Be nice to have hackaday.io as an option. 

### ISSUE THREAD

**Issue by joereddington** [openassistive/OpenATFrontEnd#36]
Was trying to add https://hackaday.io/project/25757-toowheels-the-opensource-wheelchair but got the 'unknown url' given.  

Might be worth adding - particularly since the hackaday prize this year was about assistive tech and they put up/host quite a lot of relevant projects.

**Comment by willwade** [comment]
Cool. Thanks @joereddington :) Good idea.

(Note to self.. A lot of the data can be found in the `<meta property="og:t..` items. Whats kind of interesting is that a lot of projects are duplicating their content on hacakday - either using GitHub/Dropbox/Whatever for their original source files..)

For now - I'll do it the text file way..

(Interesting that project. [Motivation](https://www.motivation.org.uk/our-design-philosophy) do something similar but vary their design depending on the country.. anyway..)

**Comment by willwade** [comment]
nearly there with this. https://github.com/openassistive/OpenATBackend/commit/08fc8469e5452816a4859822aa3f90395dea4333  - just cant work out why hackaday urls aren't getting picked up by the service

(There is a real problem though - a lot of hackaday projects are really just ideas - with some not getting far at all - not being critical (some are FASCINATING!!) but some of these don't fit with the other fully fledged projects on OpenAT. As a result they get tagged with 'in-development' by default (a user can edit it)).

**Comment by willwade** [comment]
closed (https://github.com/openassistive/OpenATBackend/commit/d7d694ef0de6351c00e5448c7f49841c4515611b)
