### ISSUE TITLE
Need a way of checking if short-title exists

### ISSUE THREAD

**Issue by willwade** [openassistive/OpenATFrontEnd#5]
When adding let user know if the project already exists. Maybe this is better done in backend?

**Comment by hosseinzoda** [comment]
It's better to be on backend

**Comment by hosseinzoda** [comment]
1. When user enters an existing project. Checking it would be better be done on backend
2. For validating "short-title" as required. Easier to be on frontend.

**Comment by willwade** [comment]
@hosseinamin are you able to pick the one up. My guess is something like this...

`'use strict';

function saveItemList(){
var github = require('octonode');
var client = github.client();
var ghrepo = client.repo('openassistive/OpenATFrontend');
var list = ghrepo.contents('contents/item'); //path
// Read list and store to file..
}
 
`

Which would be called about here: https://github.com/openassistive/OpenATBackend/blob/master/js/savejson/savejson.controller.js#L48 

(so get list after each save)

And then it would have to read that file each time for each service.. 

e.g. in each : https://github.com/openassistive/OpenATBackend/tree/master/js/services

Not as urgent but it makes sense you doing this as you know the frontend.. (and I think this should be done before going live as we want to avoid overwrites or duplicate files being made)

**Comment by hosseinzoda** [comment]
My thoughts. 
1. api call GET can tell if the project already exists or not. `service + project_id` can make a unique page for each project. We can set the item name from these info.
2. What if we have another api call to get to know when new build is finished.

**Comment by willwade** [comment]
1. Project_id = short_title currently. Are you proposing changing that?
2. Easy. Done already : https://www.netlify.com/docs/webhooks/ we can the use netlify incoming webhook to trigger this when "Deploy succeeded"

**Comment by hosseinzoda** [comment]
@willwade 
> 1. Project_id = short_title currently. Are you proposing changing that?

Yes. This helps with uniqueness of projects.

**Comment by willwade** [comment]
So what are you proposing? Something like "github-sawat" ?

**Comment by hosseinzoda** [comment]
Like this. "github/hosseinamin/reaction-test-02"

**Comment by hosseinzoda** [comment]
We can define permalinks to make it like this. And actual files can be like this "github_hosseinamin_reaction...".
Although it's better to have directories. I think there's a limit on how much file can be in a directory.

**Comment by willwade** [comment]
Problem with that idea - we want the /item to be named anything. Reason being we can add directly via git and not using API. Hmm. A different idea. 
A service (/createIndexCache) that grabs all /items/*.md

Creates a file locally that is a Json file storing:
short_title, URL

On /service/ call check to see if either URL or short_title in index. If it is carry on but warn user duplicate exists - and provide link to file.

**Comment by hosseinzoda** [comment]
good idea. We can even use a small database for more efficiency.

**Comment by willwade** [comment]
Cool. Would also need to run on intital run of course

**Comment by willwade** [comment]
closing this for now.. Putting issues in Backend.
