### ISSUE TITLE
Open homepage on clicking site's logo.

### ISSUE THREAD

**Issue by hosseinzoda** [openassistive/OpenATFrontEnd#9]
Currently i don't an option for it.

**Comment by hosseinzoda** [comment]
Oh. Home button is at bottom

**Comment by willwade** [comment]
This ok now? 
Bear in mind that in the original tranquilpeak theme there is the algolia search stuff - that (used to be anyway) triggered by clicking in the top right. I think until the upstream Hugo-tranquilpeak project builds in the full site search stuff we should keep clear of that maybe. Take a look at http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/ and https://github.com/kakawait/hugo-tranquilpeak-theme/issues/8 to see what I'm going on about (one of reasons why we picked this theme)

**Comment by willwade** [comment]
I see what you are on about now! Clicking on the top left logo in the toolbar brings the about popup. Could do with changing this (So - top left logo ->  /, remove "Home" link in the toolbar)

**Comment by hosseinzoda** [comment]
So do i change to a link to home page?

**Comment by willwade** [comment]
Yes 👍
